# -*- coding: utf-8 -*-
"""Four_Threads.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8slEOAOZ-NGIUj0kOD5THzKh0ZXTCOI
"""

import threading  #Thread Library
import time       #Time Library

s = ''    #Initializing Global variable as string

def shifttext(text, shift):   #Shifiting function
  a = ord('a')    #returns unicode of a
                #chr returns unicode string of one character
  return ''.join(chr((ord(char) - a + shift) % 26 + a) 
  for char in text.lower())   #converting to lower for ASCII code

# def inp_func():   #Input function
#   print("")
#   print("       *-*- Input String Thread -*-*")
#   print("")

#   global s    #Global variable
#   s = input("Enter a String: ")   #taking input from user

def inp_func():   #Input function
  print("")
  print("       *-*- Input String Thread -*-*")
  print("")

  global s  #Global variable

  while True:
    s = input("Enter a String: ")  #taking input from user
    s1 = s.replace(" ", '')
                        #Exception Handling
    try:
      if not s1.isalpha():
        raise ValueError
    except ValueError:      
        print('Error!! Input Valid String (Alphabets).')
        continue
    else:
        return s


def rev_func():  #Reversing function
  print("")
  print("       *-*- Reversing String Thread -*-*")
  print("")

  global s    #Global variable
  rev = s[::-1]     #Reversing string
  print("Original String:", s) 
  print("Reversed String:", rev) 


def cap_func():     #Capitalization function
  print("")
  print("       *-*- Capitalizing String Thread -*-*")
  print("")
  
  global s    #Global variable
  cap = s.upper()   #Upp
  print("Original String:", s) 
  print("Capital String:", cap) 

def shft_func():    #Shifting function
  print("")
  print("       *-*- Shifting String Thread -*-*")
  print("")
  
  global s    #Global variable
  n = int(input("Enter how many times you want to Shift: "))
  print("\nOriginal String:", s)
  rs = s.replace(" ", "")
  print("\nString after removing Spaces:", rs) 
  shft = shifttext(rs, n)
  print("Shifted String:", shft) 
                 

      #1st Thread Input thread
t1 = threading.Thread(target = inp_func, args=()) 
      #2nd Thread Reverse thread
t2 = threading.Thread(target = rev_func, args=()) 
      #3rd Thread Capital thread
t3 = threading.Thread(target = cap_func, args=()) 
      #4th Thread Shifting thread
t4 = threading.Thread(target = shft_func, args=()) 

t1.start()    #starting thread 1

t1.join()   #ending thread 1
            #and then starting remaining threads

t2.start() #starting thread 2

t3.start() #starting thread 3

t4.start() #starting thread 4

t4.join()